### ISSUE TITLE
Literature

### ISSUE THREAD

**Issue by NVessel** [joklawitter/GraphGenerators#2]
Hello! Could you please tell me what books and articles you were using in your work?

**Comment by joklawitter** [comment]
I haven't used any literature directly, but of course I know the graph classes from somewhere.
- lectures at uni
- Diestel's Graph Theory book
- graphclasses.org
- Wikipedia

If you tell me what you need it for, I might be able to give better suggestions.

**Comment by NVessel** [comment]
> 
> 
> I haven't used any literature directly, but of course I know the graph classes from somewhere.
> 
>     * lectures at uni
> 
>     * Diestel's Graph Theory book
> 
>     * graphclasses.org
> 
>     * Wikipedia
> 
> 
> If you tell me what you need it for, I might be able to give better suggestions.

I'd like to use it in my annual work dedicated to planar graphs generation

**Comment by joklawitter** [comment]
Then you might be interested in [plantri](http://users.cecs.anu.edu.au/~bdm/plantri/).

**Comment by joklawitter** [comment]
Then you might be interested in [plantri](http://users.cecs.anu.edu.au/~bdm/plantri/) and the generators from [OGDF](https://ogdf.uos.de/doc/group__graph-generators.html).

**Comment by NVessel** [comment]
Yeah, thanks, but I have to do it manually, not from ready solutions
